version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "data-fetcher-fupa-team-players-dev"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1j7hmnx97h73u"
s3_prefix = "data-fetcher-fupa-team-players-dev"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["DataFetcherFupaTeamsPlayersDev=084534280195.dkr.ecr.eu-central-1.amazonaws.com/edet"]
