AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: > 
  SAM Template for data_fetcher_fupa_teams_players

Parameters:
  stage:
    Type: String
    AllowedValues:
      - dev
      - prod

Globals:
  Function:
    Timeout: 10
    Environment:
      Variables:
        STAGE: !Ref stage

Resources:
  DataFetcherFupaTeamsPlayers:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "data-fetcher-fupa-team-players-${stage}"
      PackageType: Image
      Role: arn:aws:iam::084534280195:role/edet-lambda-rds-fullaccess
      MemorySize: 128
      Tags:
        project: edet
      Description: !Sub "Fetches Players for all Teams in general.all_teams - ${stage}"
      Events:
        ScheduledEvent:
          Type: Schedule
          Properties:
            Name: !Sub "data-fetcher-fupa-team-players-${stage}-scheduledevent"
            Description: scheduled event to fetch players for all teams
            Schedule: cron(0 03 * * ? *)
    Metadata:
      DockerTag: python3.7-v1
      DockerContext: ./data_fetcher_fupa_team_players
      Dockerfile: Dockerfile

Outputs:
  DataFetcherFupaTeamsPlayers:
    Description: "Function to get Players of Teams from Fupa"
    Value: !GetAtt DataFetcherFupaTeamsPlayers.Arn
