AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: > 
  SAM Template for edet_fupa_get_standings_of_teams

Parameters:
  stage:
    Type: String
    AllowedValues:
      - dev
      - prod
  secret:
    Type: String
  region:
    Type: String

Globals:
  Function:
    Timeout: 60
    Environment:
      Variables:
        STAGE: !Ref stage
        DB: !Sub edet_${stage}
        SOURCE_TABLE: sources.teams_source
        SECRET: !Ref secret
        REGION: !Ref region

Resources:
  EdetFupaGetStandingsOfTeams:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "edet-fupa-get-standings-of-teams-${stage}"
      PackageType: Image
      Role: arn:aws:iam::084534280195:role/edet-lambda-rds-fullaccess
      MemorySize: 128
      Tags:
        project: edet
      Description: !Sub "Fetches Standings for all teams in source - ${stage}"
      Events:
        ScheduledEvent:
          Type: Schedule
          Properties:
            Name: !Sub "edet-fupa-get-standings-of-teams-${stage}-scheduledevent"
            Description: scheduled event to fetch standings of teams
            Schedule: cron(0 03 * * ? *)
    Metadata:
      DockerTag: python3.7-v1
      DockerContext: ./edet_fupa_get_standings_of_teams
      Dockerfile: Dockerfile

Outputs:
  EdetFupaGetStandingsOfTeams:
    Description: "Function to get Players of Teams from Fupa"
    Value: !GetAtt EdetFupaGetStandingsOfTeams.Arn
